{% set name = "remotior-sensus" %}
{% set version = "0.0.50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/remotior_sensus-{{ version }}.tar.gz
  sha256: 27d619927a52a9d96663f7807d97d3f0b311ca850ad732d38740935817eb6407

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - numpy
    - scipy
    - gdal

test:
  imports:
    - remotior_sensus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://fromgistors.blogspot.com/p/remotior-sensus.html
  dev_url: https://github.com/semiautomaticgit/remotior_sensus
  doc_url: https://remotior-sensus.readthedocs.io
  summary: Remotior Sensus is software to process remote sensing and GIS data
  license: GPL-3.0-or-later
  license_file:
    - src/remotior_sensus/COPYING

extra:
  recipe-maintainers:
    - semiautomaticgit
